version: '3'

services:
  zookeeper:
    image: zookeeper:3.4.11
    hostname: zookeeper # 集群下可命名为zoo1等格式
    container_name: zookeeper # 集群下可命名为zoo1等格式
    ports:
      - "2181:2181" # 2181端口提供给client访问
    #  集群下配置，2888端口为集群内机器通讯使用，3888为选举leader使用
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_SERVER: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888
