version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # volumes:
    #   - "./sql-init:/docker-entrypoint-initdb.d:ro"
    networks:
      - cloud
  rabbitMQ:
    image: rabbitmq:3.8.19-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=puuaru
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - cloud

networks:
  cloud:
