version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # volumes:
    #   - "./sql-init:/docker-entrypoint-initdb.d:ro"
    networks:
      - cloud
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -server -bootstrap -ui -bind 127.0.0.1 -client 0.0.0.0
    networks:
      - cloud
networks:
  cloud:
