version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # volumes:
    #   - "./sql-init:/docker-entrypoint-initdb.d:ro"
    networks:
      - cloud
  # zookeeper单机单实例的配置
  zookeeper:
    image: zookeeper:3.6.0
    hostname: zookeeper # 集群下可命名为zoo1等格式
    container_name: zookeeper # 集群下可命名为zoo1等格式
    ports:
      - "2181:2181" # 2181端口提供给client访问
    #  集群下配置，2888端口为集群内机器通讯使用，3888为选举leader使用
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_SERVER: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888
    networks:
      - cloud

networks:
  cloud:
